.TH "GLCHESS" "6" 
.SH "NAME" 
glchess \(em A 3D chess application 
.SH "SYNOPSIS" 
.PP 
\fBglchess\fR 
.SH "DESCRIPTION" 
.PP 
\fBglchess\fR is a 3D chess application for 
GTK+ which supports CECP compatible artificial intelligences. 
.PP 
More information can be found at http://glchess.sourceforge.net. 
.SH "SEE ALSO" 
.PP 
gnuchess(6), crafty(6), amy(6), faile(6), xboard(6). 
.SH "AUTHOR" 
.PP 
glChess and this manual page were written by Robert Ancell bob27@users.sourceforge.net. 
Permission is granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Wed 06 Jun 2007, 21:55 
