.TH "GNOME CHESS" "6" "2014\-02\-15" "GNOME"
.SH "NAME" 
gnome-chess \(em A simple chess application for GNOME
.SH "SYNOPSIS" 
.PP 
\fBgnome-chess\fR 
.SH "DESCRIPTION" 
.PP 
\fBgnome-chess\fR is a 2D/3D chess application, previously known as glchess.
It supports both CECP- and UCI-compatible artificial intelligences.
.PP 
More information can be found at https://wiki.gnome.org/Apps/Chess
.SH "SEE ALSO" 
.PP 
gnuchess(6), crafty(6), amy(6), faile(6), xboard(6). 
.SH "AUTHOR" 
.PP 
GNOME Chess and this manual page were written by Robert Ancell bob27@users.sourceforge.net. 
Permission is granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL.
